import torch
from matplotlib import pyplot as plt
from torch.distributions import (
    Gamma,
    Exponential,
    Categorical,
    Normal,
    MixtureSameFamily,
    Laplace,
    StudentT,
)

from sampling.util import init_matplotlib


# Utility function that evaluates a function f at the input x in chunks for memory efficiency
def evaluate_chunked(f, x, chunk_size=100):
    return torch.cat([f(x_chunk) for x_chunk in torch.split(x, chunk_size)])


def laplace_main(b: float) -> None:
    # Basic sanity check
    assert b > 0.0

    # Construct the latent distribution
    latent_dist = Exponential(1.0 / (2.0 * (b ** 2)))

    # Approximate the GSM with a GMM by means of a grid approximation
    dtype = torch.float64
    eps, n = 0.5e-6, 150_000

    # The grid points are generated by equally spacing [eps, 1 - eps] and using the inverse CDF to compute the
    # corresponding variances
    p = torch.linspace(eps, 1.0 - eps, n, dtype=dtype)
    z = latent_dist.icdf(p)

    # Compute the GMM parameters
    f = torch.exp(latent_dist.log_prob(z))
    w = 0.5 * (f[1:] + f[:-1]) * (z[1:] - z[:-1])
    variances = (z[1:] + z[:-1]) / 2.0

    # Construct a scalar GMM with n - 1 components
    mixtures = Categorical(w)
    components = Normal(torch.zeros_like(variances), torch.sqrt(variances))
    p_gmm = MixtureSameFamily(mixtures, components)

    # Plot the GSM approximation
    p_gt = Laplace(loc=0.0, scale=b)
    xmin, xmax, points = -10.0, 10.0, 10_000

    # PDFs
    x = torch.linspace(xmin, xmax, points, dtype=dtype)
    plt.figure(figsize=(10, 10))
    plt.plot(x, torch.exp(p_gt.log_prob(x)), label="Laplace")
    plt.plot(x, evaluate_chunked(lambda x_chunk: torch.exp(p_gmm.log_prob(x_chunk)), x), "--", label="GSM")
    plt.xlabel("$x$")
    plt.ylabel("Probability Density")
    plt.xlim([xmin, xmax])
    plt.ylim(bottom=0.0)
    plt.legend()
    plt.tight_layout()

    # CDFs
    plt.figure(figsize=(10, 10))
    plt.plot(x, p_gt.cdf(x), label="Laplace")
    plt.plot(x, evaluate_chunked(p_gmm.cdf, x), "--", label="GSM")
    plt.xlabel("$x$")
    plt.ylabel("Cumulative Distribution Function")
    plt.xlim([xmin, xmax])
    plt.ylim(bottom=0.0)
    plt.legend()
    plt.tight_layout()


def student_t_main(df: float) -> None:
    # Basic sanity check
    assert df > 0.0

    # Construct the latent distribution
    latent_dist = Gamma(df / 2.0, df / 2.0)

    # Approximate the GSM with a GMM by means of a grid approximation
    dtype = torch.float64
    z_min, z_max, n = 0.5e-6, 20.0, 100_000

    # PyTorch's Gamma does not implement the inverse CDF, so the grid points are generated by equally spacing the
    # precisions over the interval [z_min, z_max], beyond which the latent distribution has negligible mass
    z = torch.linspace(z_min, z_max, n, dtype=dtype)

    # Compute the GMM parameters
    f = torch.exp(latent_dist.log_prob(z))
    w = 0.5 * (f[1:] + f[:-1]) * (z[1:] - z[:-1])
    precisions = (z[1:] + z[:-1]) / 2.0
    variances = 1.0 / precisions

    # Construct a scalar GMM with n - 1 components
    mixtures = Categorical(w)
    components = Normal(torch.zeros_like(variances), torch.sqrt(variances))
    p_gmm = MixtureSameFamily(mixtures, components)

    # Plot the GSM approximation
    p_gt = StudentT(df=df)
    xmin, xmax, points = -10.0, 10.0, 10_000

    # PDFs
    x = torch.linspace(xmin, xmax, points, dtype=dtype)
    plt.figure(figsize=(10, 10))
    plt.plot(x, torch.exp(p_gt.log_prob(x)), label="Student-t")
    plt.plot(x, evaluate_chunked(lambda x_chunk: torch.exp(p_gmm.log_prob(x_chunk)), x), "--", label="GSM")
    plt.xlabel("$x$")
    plt.ylabel("Probability Density")
    plt.xlim([xmin, xmax])
    plt.ylim(bottom=0.0)
    plt.legend()
    plt.tight_layout()

    # CDFs
    plt.figure(figsize=(10, 10))
    # PyTorch's StudentT does not implement the CDF, so we compute it by numerical integration
    pdf_gt = torch.exp(p_gt.log_prob(x))
    inner = torch.cat((torch.zeros(1, dtype=dtype), torch.cumulative_trapezoid(pdf_gt, x)))
    cdf_gt = (1.0 - inner[-1]) / 2.0 + inner
    plt.plot(x, cdf_gt, label="Student-t")
    plt.plot(x, evaluate_chunked(p_gmm.cdf, x), "--", label="GSM")
    plt.xlabel("$x$")
    plt.ylabel("Cumulative Distribution Function")
    plt.xlim([xmin, xmax])
    plt.ylim(bottom=0.0)
    plt.legend()
    plt.tight_layout()


# These examples numerically demonstrate that the GSM representations of the Laplace and Student-t distribution given in
# Table 1 of the paper are correct
if __name__ == "__main__":
    # Load global plotting settings
    init_matplotlib(comet=False)

    # Show that the GSM representation of the Laplace distribution is correct
    laplace_main(b=1.0)

    # Show that the GSM representation of the Student-t distribution is correct
    student_t_main(df=2.6)

    plt.show()
